### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by linzexin022**

### CODE REVIEW

**Comment by FoundationGames** [comment]
This will be merged soon to be included with the next update. Thanks!

**Comment by FoundationGames** [comment]
I just wanted to let you know that I will be pushing new features and the translation will need to be updated further, so this will not be merged until the full release of 1.2.

**Comment by linzexin022** [comment]
I'm now translation for the BETA version.
What is the "hacked sandwich"?

**Comment by linzexin022** [comment]
@FoundationGames 
Fully updated Chinese (Simplified) translations for the 1.2-BETA 1 version.
CurseForge Credit: Godzmoline.

**Comment by FoundationGames** [comment]
Thanks for the updates! Glad to know players in China will be able to have updated translations ready.

**Comment by FoundationGames** [comment]
This has been merged into `master`, but I will make sure to add the translation file to the `indev` branch.

**Pull request merged**
